### ISSUE TITLE
怎么创建了又不写

### ISSUE THREAD

**Issue by beary** [Yaphiss/Design-Patterns#1]
快写啊，等你笔记

**Comment by Yaphiss** [comment]
Hi Beary,


Thanks for your kindly reply, I am so busy at this time, and I will update the knowledge right if I have time.


Thanks,

Xavier



在 2020-01-17 20:08:21，"beary" <notifications@github.com> 写道：

快写啊，等你笔记

**Comment by beary** [comment]
Hi Xavier,

OK, I'll keep focusing. If you have any updates, let me know.

Regards,

Beary



Get Outlook for Android<https://aka.ms/ghei36>

________________________________
